package Project_Euler;

/*
   Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
public class Problem2 {

  public static void main(String[] args) {
    int first = 1, second = 1;
    int sum = 0, evenSum = 0;

    while (sum < 4000000) {
      sum = first + second;
      first = second;
      second = sum;

      if (sum % 2 == 0) {
        evenSum = evenSum + sum;
      }
    }

    System.out.println(evenSum);
  }
}
